/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.dnd.api;

import io.dnd.model.User;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-18T08:27:44.937Z")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "", nickname = "login", notes = "allow a user to connect", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "no body", response = Object.class),
        @ApiResponse(code = 401, message = "Wrong password or username"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/login",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Object> login(@ApiParam(value = "the user (name and password)" ,required=true )  @Valid @RequestBody User user);

}
