version: '2'
services:
  mysql:
    build: ../images/mysql
    environment: 
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db
  server-log:
    build: ../images/server-log
    ports:
        - "8090:8090"
    links:
     - mysql:db
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.server-log.rule=PathPrefix(`/log`)"
     - "traefik.http.middlewares.strip-log.stripprefix.prefixes=/log"
     - "traefik.http.routers.server-log.middlewares=strip-log"
  server-application:
    build: ../images/server-application
    ports:
        - "8091:8091"
    links:
     - mysql:db
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.server-application.rule=PathPrefix(`/app`)"
     - "traefik.http.middlewares.strip-app.stripprefix.prefixes=/app"
     - "traefik.http.routers.server-application.middlewares=strip-app"
  reverse-proxy:
    image: traefik:v2.1.2
    command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "2020:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
       
  
  