version: '2'
services:
  mysql:
    build: ../images/mysql
    environment: 
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db
  server-log:
    build: ../images/server-log
    ports:
        - "8090:8090"
    links:
     - mysql:db
  server-application:
    build: ../images/server-application
    ports:
        - "8091:8091"
    links:
     - mysql:db